from enum import Enum, auto
class Action(Enum):
    FILTER = auto()
    RESET = auto()
    RESEND = auto()
    BACK = auto()
    PLAY = auto()
    PAUSE = auto()
    STOP = auto()
    BEG = auto()
    END = auto()
    REV = auto()
    FWD = auto()
    SPDUP = auto()
    SPDDW = auto()
    RANGE = auto()
    MIN = auto()
    MAX = auto()
    SAVE = auto()
    PLAYMOVE = auto()

    PROT = auto()
    ARP = auto()
    DNS = auto()
    IP = auto()
    TCP = auto()
    UDP = auto()
    HTTP = auto()
    SSH = auto()
    ICMP = auto()
    IGMP = auto()
